name: Rebuild Noble Multi-Arch Container

on:
  push

jobs:
  build-noble-multiarch:
    name: Build Multi-Arch Noble Container
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Noble Image
        uses: docker/build-push-action@v5
        with:
          file: src/test/docker/noble/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wihobbs/testenv:noble
